# Generated by Django 3.1.4 on 2020-12-06 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postandcomment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='global', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='testPost'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='testContent'),
        ),
    ]
