# Generated by Django 3.1.4 on 2020-12-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postandcomment', '0003_auto_20201206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postandcomment.community'),
        ),
    ]
