# Generated by Django 3.1.4 on 2020-12-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postandcomment', '0008_auto_20201206_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
